version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
executors:
  test-env:
    docker:
      - image: 'cypress/base:10'
        environment:
          PGUSERNAME: postgres
          PGPASSWORD: salasana
      #- image: 'circleci/postgres:10.6-ram'
      #  environment:
      #    POSTGRES_PASSWORD: salasana
      #    POSTGRES_USER: postgres
jobs:
  create-db:
    executor: test-env
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run db:create
      - run: npm run db:migrate
      - run: npm run db:seed:all
  release:
    executor: test-env
    steps:
      - attach_workspace:
          at: ~/
      - run: echo MOCK_RELEASING, BOOM!
workflows:
  build-test-deploy:
    jobs:
      - cypress/install:
          executor: test-env
      - create-db:
          requires:
            - cypress/install
      - cypress/run:
          executor: test-env
          requires:
            - create-db
          build: npm run build
          start: npm start
          wait-on: 'http-get://localhost:8000'
          # record: true
      - release:
          requires:
            - cypress/run
