version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
  dockerhub: circleci/docker@0.5.1
executors:
  test:
    docker:
      - image: 'cypress/base:10'
        environment:
          NODE_ENV: test
  test-db:
    docker:
      - image: 'cypress/base:10'
        environment:
          PGUSERNAME: postgres
          PGPASSWORD: salasana
          NODE_ENV: test
      - image: 'circleci/postgres:10.6-ram'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: salasana
jobs:
  release:
    executor: test
    parameters:
      tag:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run: echo Pretending to release circle-test:<< parameters.tag >>, BOOM!
workflows:
  build-test-deploy:
    jobs:
      - cypress/install:
          executor: test
      - cypress/run:
          executor: test-db
          requires:
            - cypress/install
          build: npm run test:build
          start: npm run test:start
          wait-on: 'http-get://localhost:8000'
          # record: true
      - release:
          requires:
            - cypress/run
          tag: 'staging'
          filters:
            branches:
              only: trunk
      - dockerhub/publish:
          requires:
            - cypress/run
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          filters:
            branches:
              only: master
