version: 2.1
executors:
  install:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

jobs:
  test:
    executor: install
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "MOCK TEST RUN!"

workflows:
  test:
    jobs:
      - test
