version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
executors:
  cypress-env:
    docker:
      - image: 'cypress/base:10'
    environment:
      FOO: foo
      BAR: bar
jobs:
  release:
    executor: cypress-env
    steps:
      - attach_workspace:
          at: ~/
      - run: echo MOCK_RELEASING, BOOM!
workflows:
  build-test-deploy:
    jobs:
      - cypress/install:
          executor: cypress-env
          build: npm run build
      - cypress/run:
          executor: cypress-env
          requires:
          - cypress/install
          start: npm start
          # wait-on: 'http-get://localhost:8000'
          # record: true
      - release:
          requires:
            - cypress/run
