version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
  dockerhub: circleci/docker@0.5.1
executors:
  test:
    docker:
      - image: 'cypress/base:10'
        environment:
          NODE_ENV: test
      - image: 'circleci/postgres:10.6-ram'
workflows:
  build-test-deploy:
    jobs:
      - cypress/run:
          executor: test
          build: npm run test:setup
          start: npm run test:start
          wait-on: 'http-get://localhost:8000'
      - dockerhub/publish:
          requires:
            - cypress/run
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          filters:
            branches:
              only: trunk
      - dockerhub/publish:
          requires:
            - cypress/run
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          filters:
            branches:
              only: master
